Aventi/Aventi/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('de/register/', user_views.register, name='register'),
    path('fr/register/', user_views.register, name='register-fr'),
    path('en/register/', user_views.register, name='register-en'),

    path('de/profile/', user_views.profile, name='profile'),
    path('fr/profile/', user_views.profile_fr, name='profile-fr'),
    path('en/profile/', user_views.profile_en, name='profile-en'),

    path('de/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('fr/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login-fr'),
    path('en/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login-en'),

    path('de/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('fr/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-fr'),
    path('en/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout-en'),

    path('de/password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('fr/password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset-fr'),
    path('en/password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset-en'),

    path('de/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('fr/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('en/password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),

    path('de/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('fr/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm-fr'),
    path('en/password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm-en'),

    path('de/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('fr/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('en/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

    path('', include('seminar.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aventi/seminar/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home_view, name='seminar-home'),
    path('de/', views.home_view, name='seminar-home'),
    path('fr/', views.home_fr_view, name='seminar-home-fr'),
    path('en/', views.home_en_view, name='seminar-home-en'),

    path('de/about/', views.about_view, name='seminar-about'),
    path('fr/about/', views.about_view_fr, name='seminar-about-fr'),
    path('en/about/', views.about_view_en, name='seminar-about-en'),

    path('de/imprint/', views.imprint_view, name='seminar-imprint'),
    path('fr/imprint/', views.imprint_view_en, name='seminar-imprint-fr'),
    path('en/imprint/', views.imprint_view_en, name='seminar-imprint-en'),

    path('de/privacypolicy/', views.privacypolicy_view, name='seminar-privacypolicy'),
    path('fr/privacypolicy/', views.privacypolicy_view_fr, name='seminar-privacypolicy-fr'),
    path('en/privacypolicy/', views.privacypolicy_view_en, name='seminar-privacypolicy-en'),

    path('de/contact/', views.contact_view, name='seminar-contact'),
    path('fr/contact/', views.contact_view, name='seminar-contact-fr'),
    path('en/contact/', views.contact_view, name='seminar-contact-en'),

    path('de/<slug:slug>/form/', views.form_view, name='seminar-form'),
    path('fr/<slug:slug>/form/', views.form_view_fr, name='seminar-form-fr'),
    path('en/<slug:slug>/form/', views.form_view_en, name='seminar-form-en'),

    path('de/<slug:slug>/', views.post_detail_view, name='post-slug'),
    path('fr/<slug:slug>/', views.post_detail_view_fr),
    path('en/<slug:slug>/', views.post_detail_view_en),

    path('<slug:slug>/ordersummary/', views.order_summary_view, name='ordersummary'),

    path('de/<slug:slug>/ordersummary/data', views.order_summary_view_data, name='ordersummary-data'),
    path('fr/<slug:slug>/ordersummary/data', views.order_summary_view_data_fr, name='ordersummary-data-fr'),
    path('en/<slug:slug>/ordersummary/data', views.order_summary_view_data_en, name='ordersummary-data-en'),

    path('<slug:slug>/payment_complete/', views.payment_complete, name='payment_complete'),
    #path('fr/<slug:slug>/payment_complete/', views.payment_complete, name='payment_complete-fr'),
    #path('en/<slug:slug>/payment_complete/', views.payment_complete, name='payment_complete-en'),

    path('de/<slug:slug>/checkout', views.checkout_view, name='checkout'),
    path('fr/<slug:slug>/checkout', views.checkout_view_fr, name='checkout-fr'),
    path('en/<slug:slug>/checkout', views.checkout_view_en, name='checkout-en'),

    path('error', views.error, name='error'),
    path('success', views.success, name='success'),

    path('<slug:slug>/confirmation/', views.confirm_order, name='confirmation'),

    path('csv', views.export_csv, name='test')
]

Aventi/seminar/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.conf import settings
from django_countries.fields import CountryField
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404

class Post(models.Model):
    title = models.CharField(max_length = 255)
    title_en = models.CharField(max_length = 255, blank=True)
    title_fr = models.CharField(max_length = 255, blank=True)
    homepage_image = models.ImageField(upload_to="media/home")
    homepage_content = models.TextField()
    homepage_english_content = models.TextField(null=True)
    homepage_french_content = models.TextField(null=True)
    date_posted = models.DateTimeField(default = timezone.now)
    program_days = models.ManyToManyField('ProgramDay',  through='Post_ProgramDay')
    slug = models.SlugField (
    verbose_name = "Slug", allow_unicode = True, 
    unique=True, blank = True, null = True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug: self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    #def check_if_already_ordered(self):
        #return reverse("order-check", kwargs={'slug': self.slug})
    
    class Meta:
        verbose_name_plural = "        Post"


class Description(models.Model):
    related_post = models.OneToOneField(Post, on_delete=models.CASCADE, primary_key=True,)
    content = models.TextField()
    english_content = models.TextField(null=True)
    french_content = models.TextField(null=True)
    image = models.ImageField(upload_to="media/description", blank=True)

    def __str__(self):
        return "Description for "+self.related_post.title

    class Meta:
        verbose_name_plural = "       Description"
        
class ProgramDay(models.Model):
    posts = models.ManyToManyField('Post', through='Post_ProgramDay')
    day = models.CharField(max_length=50)
    day_en = models.CharField(max_length=50)
    day_fr = models.CharField(max_length=50)
    content = models.TextField()
    english_content = models.TextField(null=True)
    french_content = models.TextField(null=True)
    image = models.ImageField(upload_to="media/ProgramDay", blank=True)
    image_source = models.CharField(max_length=250)
    #

    def __str__(self):
        return f"{self.day}"

    class Meta:
        verbose_name_plural = "      ProgramDay"

#class Image_for_description(models.Model):
#    related_description = models.OneToOneField(Description,on_delete=models.CASCADE,primary_key=True)
#    image = models.ImageField(upload_to="media/description")
#    photo_credit = models.TextField()



class Arrival(models.Model):
    related_post = models.OneToOneField(Post,on_delete=models.CASCADE,primary_key=True)
    content = models.TextField(null=True)
    english_content = models.TextField(null=True)
    french_content = models.TextField(null=True)
    image = models.ImageField(upload_to="media/arrival", blank=True)

    def __str__(self):
        return self.related_post.title

    class Meta:
        verbose_name_plural = "    Arrival"

class Price(models.Model):
    related_post = models.OneToOneField(Post,on_delete=models.CASCADE,primary_key=True)
    content = models.TextField()
    english_content = models.TextField(null=True)
    french_content = models.TextField(null=True)

    def __str__(self):
        return self.related_post.title

    class Meta:
        verbose_name_plural = "   Price"

class Registration(models.Model):
    related_post = models.OneToOneField(Post,on_delete=models.CASCADE,primary_key=True)
    content = models.TextField()
    english_content = models.TextField(null=True)
    french_content = models.TextField(null=True)
    image = models.ImageField(upload_to="media/registration", blank=True)

    def __str__(self):
        return self.related_post.title

    class Meta:
        verbose_name_plural = "   Registration"


class Item(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(default="", max_length=255)
    name_en = models.CharField(default="", max_length=255)
    name_fr = models.CharField(default="", max_length=255)
    tax_amount = models.FloatField(default=20.0)
    is_required = models.BooleanField(default=True)
    sequence = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.post.title}, {self.name}"

    class Meta:
        verbose_name_plural = "  Items"

class Component(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    orders = models.ManyToManyField('Order', through='Order_Component')
    name = models.CharField(default="", max_length=255)
    name_en = models.CharField(default="", max_length=255)
    name_fr = models.CharField(default="", max_length=255)
    price = models.FloatField(default=0)
    quantity = models.IntegerField(null=True)
    sequence = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.item.post.title}, {self.item.name}, {self.name}"
    
    def calculateFullPrice(self):
        price_taxes = self.item.tax_amount * self.price / 100
        price_with_taxes = price_taxes + self.price

        return price_with_taxes

    class Meta:
        verbose_name_plural = " Component"

class Order(models.Model):
    generated_order_id = models.CharField(default="", max_length=255)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    components = models.ManyToManyField('Component',  through='Order_Component')
    ordered_date = models.DateTimeField()

    def __str__(self):
        return f"Ordered by {self.user.username}"

    def get_total(self):
        total = 0
        
        order_components = get_list_or_404(Order_Component, order=self)
        for order_component in order_components:
            price_taxes = order_component.component.item.tax_amount * order_component.component.price / 100
            price_with_taxes = price_taxes + order_component.component.price
            total += price_with_taxes
        total = round(total, 3)
        return total

class Order_Component(models.Model):
    component = models.ForeignKey('Component', on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.order.user.username} ordered {self.component.name}"

class Post_ProgramDay(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    programday = models.ForeignKey('ProgramDay', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.post.title} has {self.programday.day}"

    class Meta:
        verbose_name_plural = "     Post_ProgramDay"

Aventi/seminar/templates/seminar/error.html
{% extends "seminar/base.html" %}
{% block content %}

<p>An error has occurred during your payment or you have cancelled your payment.
With the button you can return to the homepage.</p>
<a class="btn btn-primary btn-lg btn-block" href="{% url 'seminar-home' %}"><button id="btn" name="go_to_payment" type="button" class="btn btn-primary btn-lg btn-block"></button>
    Home
</button></a>
{% endblock content %}

Aventi/seminar/templates/seminar/form.html
{% extends "seminar/base.html" %}
{% block content %}
<h3>Ihr Bestellungsformular:</h3>
<label>Die mit * gekennzeichneten Items sind erforderlich, nicht gekennzeichnete Items sind optional.</label>
<label>Die eingeklammerte Zahl entspricht dem noch verfügbaren Bestand.</label>
<article class="media content-section">
  <div class="media-body">
    <form method="POST" action="">
      {% csrf_token %}
        {% for item in items %}
            {% if item.is_required == True %}
              <p><b><label title="{{item.name}}" class="item-required" id="{{forloop.counter}}">{{item.name}}:*</label></b></br>
            {% else %}
              <p><b><label title="{{item.name}}" class="item" id="{{forloop.counter}}">{{item.name}}:</label></b></br>
            {% endif %}
            {% for specific_component in item.component_set.all %}
              {% if specific_component.quantity == 0 %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}" disabled> {{specific_component.name}}: {{specific_component.calculateFullPrice}} €  (ausgebucht)
                </br>
              {% else %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}"> {{specific_component.name}}: {{specific_component.calculateFullPrice}} €   ({{ specific_component.quantity }})
                </br>
              {% endif %}
            {% endfor %}
          </p>
        {% endfor %}
      <button class="btn btn-primary btn-lg btn-block" onclick="createOrder()" value="{{ counted_items }}" name="ordersummary" type="button"
        style="left: 50%;">Buchen</button>
    </form>
  </div>
</article>

<script>
  var xhr = new XMLHttpRequest();
  var formData = new FormData();

  function createOrder() {
    var checked_components = [];
    var checked_items = [];
    var required_items = [];
    var not_required_items = [];
    var items_not_required = document.getElementsByClassName('item');
    var items_required = document.getElementsByClassName('item-required');
    var items_count = items_not_required.length + items_required.length;
    var last_index_count = 0;
    var required_items_are_selected = 0;

    Array.prototype.forEach.call(items_not_required, function(el) {
      not_required_items.push(el.title);
    });

    Array.prototype.forEach.call(items_required, function(el) {
      required_items.push(el.title);
    });

    for (var i = 1; i <= items_count; i++) {
      var components = document.getElementsByClassName('items-' + i).length;
      var concrete_item = document.getElementById(i);

      for (var j = 0; j < components; j++) {
        last_index_count++;
        var rdbutton = document.getElementById("ordersummary-" + i + "-" + last_index_count);
        if (rdbutton.checked) {
          checked_items.push(concrete_item.title);
          console.log(concrete_item.title)
          checked_components.push(rdbutton.value);
          console.log(rdbutton.value)
        }
      }
      last_index_count = 0;
    }

    Array.prototype.forEach.call(checked_items, function(el) {
      Array.prototype.forEach.call(required_items, function(required_element) {
        if(el === required_element){
          required_items_are_selected++;
        }
      });
    });

    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    
    if (required_items.length === required_items_are_selected){
      xhr.open('POST', '{{ HTTP_HOST }}/{{post.slug}}/ordersummary/', true);
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
      xhr.withCredentials = true;
      xhr.upload.onprogress = function (e) {
        //update
      };

      xhr.onload = function (e) {
        if (xhr.status === 200 && required_items.length === required_items_are_selected) {
          location.replace("{{HTTP_HOST}}/de/{{post.slug}}/ordersummary/data")
        } 
      };
      
      xhr.send(JSON.stringify({ 'components': checked_components, 'items': checked_items}));
    }
    else{
      alert("Bitte wählen Sie alle erforderlichen Items aus");
    }
  }
</script>
{% endblock content %}

Aventi/seminar/templates/seminar/form_en.html
{% extends "seminar/base.html" %}
{% block content %}
<h3>Your order:</h3>
<label>Items marked with * are required, items not marked are optional.</label>
<label>The number in brackets corresponds to the stock still available.</label>
<article class="media content-section">
  <div class="media-body">
    <form method="POST" action="">
      {% csrf_token %}
        {% for item in items %}
            {% if item.is_required == True %}
              <p><b><label title="{{item.name}}" class="item-required" id="{{forloop.counter}}">{{item.name_en}}:*</label></b></br>
            {% else %}
              <p><b><label title="{{item.name}}" class="item" id="{{forloop.counter}}">{{item.name_en}}:</label></b></br>
            {% endif %}
            {% for specific_component in item.component_set.all %}
              {% if specific_component.quantity == 0 %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}" disabled> {{specific_component.name_en}}: {{specific_component.calculateFullPrice}} €  (sold out)
                </br>
              {% else %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}"> {{specific_component.name_en}}: {{specific_component.calculateFullPrice}} €   ({{ specific_component.quantity }})
                </br>
              {% endif %}
            {% endfor %}
          </p>
        {% endfor %}
      <button class="btn btn-primary btn-lg btn-block" onclick="createOrder()" value="{{ counted_items }}" name="ordersummary" type="button"
        style="left: 50%;">Book</button>
    </form>
  </div>
</article>

<script>
  var xhr = new XMLHttpRequest();
  var formData = new FormData();

  function createOrder() {
    var checked_components = [];
    var checked_items = [];
    var required_items = [];
    var not_required_items = [];
    var items_not_required = document.getElementsByClassName('item');
    var items_required = document.getElementsByClassName('item-required');
    var items_count = items_not_required.length + items_required.length;
    var last_index_count = 0;
    var required_items_are_selected = 0;

    Array.prototype.forEach.call(items_not_required, function(el) {
      not_required_items.push(el.title);
    });

    Array.prototype.forEach.call(items_required, function(el) {
      required_items.push(el.title);
    });

    for (var i = 1; i <= items_count; i++) {
      var components = document.getElementsByClassName('items-' + i).length;
      var concrete_item = document.getElementById(i);

      for (var j = 0; j < components; j++) {
        last_index_count++;
        var rdbutton = document.getElementById("ordersummary-" + i + "-" + last_index_count);
        if (rdbutton.checked) {
          checked_items.push(concrete_item.title);
          console.log(concrete_item.title)
          checked_components.push(rdbutton.value);
          console.log(rdbutton.value)
        }
      }
      last_index_count = 0;
    }

    Array.prototype.forEach.call(checked_items, function(el) {
      Array.prototype.forEach.call(required_items, function(required_element) {
        if(el === required_element){
          required_items_are_selected++;
        }
      });
    });

    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    
    if (required_items.length === required_items_are_selected){
      xhr.open('POST', '{{ HTTP_HOST }}/{{post.slug}}/ordersummary/', true);
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
      xhr.withCredentials = true;
      xhr.upload.onprogress = function (e) {
        //update
      };

      xhr.onload = function (e) {
        if (xhr.status === 200 && required_items.length === required_items_are_selected) {
          location.replace("{{HTTP_HOST}}/en/{{post.slug}}/ordersummary/data")
        } 
      };
      
      xhr.send(JSON.stringify({ 'components': checked_components, 'items': checked_items}));
    }
    else{
      alert("Please select all required items!");
    }
  }
</script>
{% endblock content %}

Aventi/seminar/templates/seminar/form_fr.html
{% extends "seminar/base.html" %}
{% block content %}
<h3>Votre bon de commande:</h3>
<label>Les éléments marqués d'un * sont obligatoires, les éléments non marqués sont optionnels.</label>
<label>Le nombre entre parenthèses correspond au stock encore disponible.</label>
<article class="media content-section">
  <div class="media-body">
    <form method="POST" action="">
      {% csrf_token %}
        {% for item in items %}
            {% if item.is_required == True %}
              <p><b><label title="{{item.name}}" class="item-required" id="{{forloop.counter}}">{{item.name_fr}}:*</label></b></br>
            {% else %}
              <p><b><label title="{{item.name}}" class="item" id="{{forloop.counter}}">{{item.name_fr}}:</label></b></br>
            {% endif %}
            {% for specific_component in item.component_set.all %}
              {% if specific_component.quantity == 0 %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}" disabled> {{specific_component.name_fr}}: {{specific_component.calculateFullPrice}} €  (plein)
                </br>
              {% else %}
                <input type="radio" class="items-{{forloop.parentloop.counter}}"
                  id="ordersummary-{{forloop.parentloop.counter}}-{{forloop.counter}}" name="{{ item.name }}"
                  value="{{specific_component.name}}"> {{specific_component.name_fr}}: {{specific_component.calculateFullPrice}} €   ({{ specific_component.quantity }})
                </br>
              {% endif %}
            {% endfor %}
          </p>
        {% endfor %}
      <button class="btn btn-primary btn-lg btn-block" onclick="createOrder()" value="{{ counted_items }}" name="ordersummary" type="button"
        style="left: 50%;">réserver</button>
    </form>
  </div>
</article>

<script>
  var xhr = new XMLHttpRequest();
  var formData = new FormData();

  function createOrder() {
    var checked_components = [];
    var checked_items = [];
    var required_items = [];
    var not_required_items = [];
    var items_not_required = document.getElementsByClassName('item');
    var items_required = document.getElementsByClassName('item-required');
    var items_count = items_not_required.length + items_required.length;
    var last_index_count = 0;
    var required_items_are_selected = 0;

    Array.prototype.forEach.call(items_not_required, function(el) {
      not_required_items.push(el.title);
    });

    Array.prototype.forEach.call(items_required, function(el) {
      required_items.push(el.title);
    });

    for (var i = 1; i <= items_count; i++) {
      var components = document.getElementsByClassName('items-' + i).length;
      var concrete_item = document.getElementById(i);

      for (var j = 0; j < components; j++) {
        last_index_count++;
        var rdbutton = document.getElementById("ordersummary-" + i + "-" + last_index_count);
        if (rdbutton.checked) {
          checked_items.push(concrete_item.title);
          console.log(concrete_item.title)
          checked_components.push(rdbutton.value);
          console.log(rdbutton.value)
        }
      }
      last_index_count = 0;
    }

    Array.prototype.forEach.call(checked_items, function(el) {
      Array.prototype.forEach.call(required_items, function(required_element) {
        if(el === required_element){
          required_items_are_selected++;
        }
      });
    });

    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    
    if (required_items.length === required_items_are_selected){
      xhr.open('POST', '{{ HTTP_HOST }}/{{post.slug}}/ordersummary/', true);
      xhr.setRequestHeader("X-CSRFToken", csrftoken);
      xhr.withCredentials = true;
      xhr.upload.onprogress = function (e) {
        //update
      };

      xhr.onload = function (e) {
        if (xhr.status === 200 && required_items.length === required_items_are_selected) {
          location.replace("{{HTTP_HOST}}/fr/{{post.slug}}/ordersummary/data")
        } 
      };
      
      xhr.send(JSON.stringify({ 'components': checked_components, 'items': checked_items}));
    }
    else{
      alert("Veuillez demander tous les articles possibles!");
    }
  }
</script>
{% endblock content %}

Aventi/seminar/templates/seminar/home_fr.html
{% extends "seminar/base.html" %}
{% block content %}
{% for post in posts %}
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="/fr/{{ post.slug }}">{{ post.title_fr }}</a></h2>
        <p class="article-content">{{ post.homepage_french_content|safe }}</p>
        <div class="hvrbox">
            <p><img src="{{ post.homepage_image.url }}" width="100%" class="hvrbox-layer_bottom" />
	        <div class="hvrbox-layer_top">
		        <div class="hvrbox-text">© Karl Bauer / WikiCommons</div>
            </div>
        </div>
        <a href="/fr/{{ post.slug }}"><button type="button" class="btn btn-primary btn-lg btn-block">Cliquez ici pour
                réserver la conférence!</button></a>
    </div>
</article>
<style>
    .hvrbox,
.hvrbox * {
	box-sizing: border-box;
}
.hvrbox {
	position: relative;
	display: inline-block;
	overflow: hidden;
	max-width: 100%;
	height: auto;
}
.hvrbox img {
	max-width: 100%;
}
.hvrbox .hvrbox-layer_bottom {
	display: block;
}
.hvrbox .hvrbox-layer_top {
	opacity: 0;
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	width: 100%;
	height: 100%;
	background: rgba(0, 0, 0, 0.6);
	color: #fff;
	padding: 15px;
	-moz-transition: all 0.4s ease-in-out 0s;
	-webkit-transition: all 0.4s ease-in-out 0s;
	-ms-transition: all 0.4s ease-in-out 0s;
	transition: all 0.4s ease-in-out 0s;
}
.hvrbox:hover .hvrbox-layer_top,
.hvrbox.active .hvrbox-layer_top {
	opacity: 1;
}
.hvrbox .hvrbox-text {
	text-align: center;
	font-size: 18px;
	display: inline-block;
	position: absolute;
	top: 50%;
	left: 50%;
	-moz-transform: translate(-50%, -50%);
	-webkit-transform: translate(-50%, -50%);
	-ms-transform: translate(-50%, -50%);
	transform: translate(-50%, -50%);
}
.hvrbox .hvrbox-text_mobile {
	font-size: 15px;
	border-top: 1px solid rgb(179, 179, 179); /* for old browsers */
	border-top: 1px solid rgba(179, 179, 179, 0.7);
	margin-top: 5px;
	padding-top: 2px;
	display: none;
}
.hvrbox.active .hvrbox-text_mobile {
	display: block;
}
</style>
{% endfor %}
{% endblock content %}

Aventi/seminar/templates/seminar/payment_complete.html
{% extends "seminar/base.html" %}
{% load static %} 
{% block content %}
<h1>About</h1>
<article onload="load()" class="media content-section">
        <form name="test" method="post" action="http://www.example.com">
            <input type="hidden" name="foo" value={{ foo }} />
            <input type="hidden" name="bar" value={{ bar }} />
        </form>
    <div class="media-body">            
            <h1>Complete</h1>
    </div>
</article>

<script type="text/javascript">
    function load()
    {
         window.document.test.submit();
         return;
    }
</script>
{% endblock content %}